"""add protocol and connection_config to devices

Revision ID: 4e405f1129b1
Revises: 4f152b34e800
Create Date: 2025-11-01 19:07:22.800918+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e405f1129b1'
down_revision: Union[str, Sequence[str], None] = '4f152b34e800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_credentials',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('credential_type', sa.Text(), nullable=False),
    sa.Column('credential_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_credentials_active', 'device_credentials', ['device_id', 'revoked_at'], unique=False)
    op.create_index('idx_device_credentials_device_id', 'device_credentials', ['device_id'], unique=False)
    
    # Add protocol column as nullable first, set default for existing rows, then make NOT NULL
    op.add_column('devices', sa.Column('protocol', sa.Text(), nullable=True))
    op.execute("UPDATE devices SET protocol = 'mqtt' WHERE protocol IS NULL")
    op.alter_column('devices', 'protocol', nullable=False)
    
    op.add_column('devices', sa.Column('connection_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'connection_config')
    op.drop_column('devices', 'protocol')
    op.drop_index('idx_device_credentials_device_id', table_name='device_credentials')
    op.drop_index('idx_device_credentials_active', table_name='device_credentials')
    op.drop_table('device_credentials')
    # ### end Alembic commands ###
