"""add device_certificates table

Revision ID: f94393f57c35
Revises: dae12d7f4ddf
Create Date: 2025-10-29 21:57:58.983071+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f94393f57c35"
down_revision: Union[str, Sequence[str], None] = "dae12d7f4ddf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_certificates",
        sa.Column("device_id", sa.Text(), nullable=False),
        sa.Column("certificate_pem", sa.Text(), nullable=False),
        sa.Column("private_key_pem", sa.Text(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("device_id"),
    )
    op.add_column(
        "devices",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.drop_index(op.f("telemetry_time_idx"), table_name="telemetry")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("telemetry_time_idx"),
        "telemetry",
        [sa.literal_column("time DESC")],
        unique=False,
    )
    op.drop_column("devices", "created_at")
    op.drop_table("device_certificates")
    # ### end Alembic commands ###
