"""command_log table for device actuation tracking

Revision ID: e5f2a9c41d7b
Revises: a7f3c9e21b4d
Create Date: 2026-09-15 21:15:00.000000+00:00

Scope: command_log table ONLY. This database is shared with other projects
(vehicle_positions, arrival_records, hourly_route_delays) and Django tables —
nothing here may touch those objects. Hand-written (never autogenerated on
the shared DB).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e5f2a9c41d7b'
down_revision: Union[str, Sequence[str], None] = 'a7f3c9e21b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # WARNING: keep this revision to command_log only — this database is shared
    # with other projects and Django, so autogenerated drop_table calls must
    # stay out (see dc7b523353d3 for the pattern).
    op.create_table(
        'command_log',
        sa.Column('id', sa.Text(), nullable=False),
        sa.Column('device_id', sa.Text(), nullable=False),
        sa.Column('action', sa.Text(), nullable=False),
        sa.Column('payload', sa.JSON(), nullable=True),
        sa.Column('req_id', sa.Text(), nullable=False),
        sa.Column('state', sa.Text(), nullable=False, server_default='requested'),
        sa.Column('ttl_sec', sa.Integer(), nullable=False, server_default='300'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('req_id'),
        sa.CheckConstraint("state IN ('requested', 'acked', 'expired', 'failed')", name='ck_command_log_state'),
    )
    op.create_index('idx_command_log_device_id', 'command_log', ['device_id'], unique=False)
    op.create_index('idx_command_log_state', 'command_log', ['state'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # Removes ONLY command_log — no other table is touched here.
    op.drop_index('idx_command_log_state', table_name='command_log')
    op.drop_index('idx_command_log_device_id', table_name='command_log')
    op.drop_table('command_log')
