#!/bin/bash
# Fresh-clone to running stack: generates gitignored runtime config
# (compose env files, PKI), builds images, starts everything, migrates.
#
# Usage: ./scripts/bootstrap.sh [--force]
#   --force  regenerate PKI even if ca.crt already exists
#
# Nothing here is committed: all generated files are gitignored.
set -euo pipefail

FORCE=0
if [ "${1:-}" = "--force" ]; then FORCE=1; fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INFRA="$ROOT/infrastructure"
CERTS="$INFRA/mosquitto/certs"
COMPOSE="docker compose -f $INFRA/compose.yml"

command -v docker >/dev/null || { echo "ERROR: docker not found" >&2; exit 1; }
command -v openssl >/dev/null || { echo "ERROR: openssl not found" >&2; exit 1; }
docker compose version >/dev/null || { echo "ERROR: docker compose plugin not found" >&2; exit 1; }

POSTGRES_USER="${POSTGRES_USER:-postgres}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-example}"
POSTGRES_DB="${POSTGRES_DB:-iot_data}"
export POSTGRES_USER POSTGRES_PASSWORD POSTGRES_DB

echo "==> 1/5 directories"
# Older checkouts may have mosquitto/ owned by UID 1883 (broker user from
# volume mounts). Reclaim it so plain file operations work below.
if [ -d "$INFRA/mosquitto" ]; then
  docker run --rm -v "$INFRA/mosquitto:/m" alpine chown -R "$(id -u):$(id -g)" /m
fi
mkdir -p "$CERTS" "$INFRA/mosquitto/data" "$INFRA/mosquitto/logs"

echo "==> 2/5 compose env (infrastructure/.env)"
if [ ! -f "$INFRA/.env" ]; then
  {
    echo "# Generated by scripts/bootstrap.sh — gitignored, safe to delete and re-run."
    echo "POSTGRES_USER=$POSTGRES_USER"
    echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
    echo "POSTGRES_DB=$POSTGRES_DB"
    echo "SECRET_KEY=$(openssl rand -hex 32)"
    echo "OPENAI_API_KEY=${OPENAI_API_KEY:-}"
  } > "$INFRA/.env"
  echo "wrote infrastructure/.env (fresh SECRET_KEY)"
else
  echo "infrastructure/.env exists, kept"
fi

echo "==> 3/5 PKI (mosquitto/certs)"
if [ -f "$CERTS/ca.crt" ] && [ "$FORCE" -eq 0 ]; then
  echo "ca.crt exists, kept (use --force to regenerate)"
else
  WORK="$(mktemp -d)"
  trap 'rm -rf "$WORK"' EXIT
  # generate_ca.sh writes ./certs relative to CWD — run it inside WORK
  # so the repo tree stays clean.
  ( cd "$WORK" && bash "$ROOT/services/device_manager/generate_ca.sh" localhost mosquitto )
  GEN="$WORK/certs"
  [ -f "$GEN/ca.crt" ] || { echo "ERROR: cert generation produced no ca.crt" >&2; exit 1; }
  mv -f "$GEN/ca.crt" "$GEN/server.crt" "$GEN/server.key" "$GEN/ca.key" "$CERTS/"
  # Empty CRL (mosquitto refuses to start if crlfile is missing)
  mkdir -p "$WORK/cadb" && touch "$WORK/cadb/index.txt" && echo 1000 > "$WORK/cadb/crlnumber"
  printf '[ ca ]\ndefault_ca = CA_default\n[ CA_default ]\ndatabase = %s/cadb/index.txt\ncrlnumber = %s/cadb/crlnumber\ndefault_md = sha256\npolicy = policy_any\n[ policy_any ]\ncommonName = supplied\n[ req ]\ndistinguished_name = req_dn\n[ req_dn ]\n' "$WORK" "$WORK" > "$WORK/openssl.cnf"
  openssl ca -gencrl -config "$WORK/openssl.cnf" \
    -keyfile "$CERTS/ca.key" -cert "$CERTS/ca.crt" \
    -out "$CERTS/ca.crl" -crldays 30
  # Service client identities (ingestion + command publisher)
  echo 2000 > "$WORK/ca.srl"
  for name in ingestion command; do
    openssl genrsa -out "$WORK/$name.key" 2048 2>/dev/null
    openssl req -new -key "$WORK/$name.key" -out "$WORK/$name.csr" -subj "/CN=mqtt-$name"
    openssl x509 -req -in "$WORK/$name.csr" -CA "$CERTS/ca.crt" -CAkey "$CERTS/ca.key" \
      -CAserial "$WORK/ca.srl" -out "$CERTS/$name.crt" -days 825 2>/dev/null
    mv -f "$WORK/$name.key" "$CERTS/$name.key"
  done
  chmod 600 "$CERTS"/*.key
  chmod 644 "$CERTS"/*.crt "$CERTS"/*.crl
  rm -rf "$WORK"
  trap - EXIT
  echo "issued CA + server (localhost,mosquitto) + empty CRL + ingestion/command identities"
fi

echo "==> 4/5 service env files (compose-network values)"
cat > "$INFRA/.env.mqi" <<EOF
# Generated by scripts/bootstrap.sh — gitignored.
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_DB=0
REDIS_PASSWORD=
MQTT_BROKER=mosquitto
MQTT_PORT=8883
MQTT_USERNAME=
MQTT_PASSWORD=
MQTT_TOPIC_PATTERN=devices/#
MQTT_KEEPALIVE=60
MQTT_TLS=true
MQTT_CA_CERT=/app/certs/ca.crt
MQTT_CLIENT_CERT=/app/certs/ingestion.crt
MQTT_CLIENT_KEY=/app/certs/ingestion.key
DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@timescaledb:5432/$POSTGRES_DB
EOF
cat > "$INFRA/.env.dbw" <<EOF
# Generated by scripts/bootstrap.sh — gitignored.
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_DB=0
REDIS_PASSWORD=
DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@timescaledb:5432/$POSTGRES_DB
CONSUMER_GROUP_NAME=db_writer
CONSUMER_NAME=worker-01
BATCH_SIZE=100
BATCH_TIMEOUT_SEC=5
PROCESSING_INTERVAL_SEC=1
MAX_RETRIES=3
TRIM_MAXLEN=10000
LOG_LEVEL=INFO
EOF
cat > "$ROOT/services/device_manager/.env" <<EOF
# Generated by scripts/bootstrap.sh — gitignored.
DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@timescaledb:5432/$POSTGRES_DB
CA_CERT_PATH=/app/certs/ca.crt
CA_KEY_PATH=/app/certs/ca.key
CRL_PATH=/app/certs/ca.crl
CERT_VALIDITY_DAYS=365
CERT_KEY_SIZE=4096
DEVICE_ID_LENGTH=8
DEVICE_MANAGER_HOST=0.0.0.0
DEVICE_MANAGER_PORT=8000
LOG_LEVEL=INFO
MQTT_BROKER=mosquitto
MQTT_PORT=8883
MQTT_TLS=true
MQTT_CA_CERT=/app/certs/ca.crt
MQTT_COMMAND_CERT=/app/certs/command.crt
MQTT_COMMAND_KEY=/app/certs/command.key
EOF
echo "wrote .env.mqi, .env.dbw, device_manager/.env"

echo "==> 5/5 build + up + migrate"
$COMPOSE build
$COMPOSE up -d
echo "waiting for timescaledb..."
for _ in $(seq 1 24); do
  docker exec infrastructure-timescaledb-1 pg_isready -U "$POSTGRES_USER" >/dev/null 2>&1 && break
  sleep 5
done
docker exec infrastructure-timescaledb-1 pg_isready -U "$POSTGRES_USER"
echo "--- service status ---"
$COMPOSE ps --format '{{.Name}} {{.State}}'
echo
echo "Done. Next steps:"
echo "  1. Create a login user:"
echo "     docker compose -f infrastructure/compose.yml exec -e DATABASE_URL=postgresql://\$POSTGRES_USER:\$POSTGRES_PASSWORD@timescaledb:5432/\$POSTGRES_DB backend python create_user.py --username admin --password <pw>"
echo "  2. Frontend: http://localhost  |  BFF: http://localhost:3000/api/dashboard/overview/"
echo "  3. Register a device: POST http://localhost:3000/api/devices/ {\"name\":\"sensor-01\",\"protocol\":\"mqtt\"}"
echo "  4. Publish: mosquitto_pub --cafile infrastructure/mosquitto/certs/ca.crt --cert device.crt --key device.key -h localhost -p 8883 -t 'devices/<id>/temperature' -m '23.5'"
echo "  OPENAI_API_KEY is ${OPENAI_API_KEY:+set (AI features live)}${OPENAI_API_KEY:-empty (AI endpoints will error; everything else works)}"
