services:

  redis:
    image: redis:8
    ports: 
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
  
  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9001:9001"
      - "8883:8883"
    volumes:
      - ./mosquitto/:/mosquitto/:Z
    restart: unless-stopped
  
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-example}
      POSTGRES_DB: ${POSTGRES_DB:-iot_data}
    ports:
      - "5432:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    restart: unless-stopped

  db-write:
    build: 
      context: ../services/db_write
    env_file:
      - .env.dbw
    depends_on:
      - timescaledb
      - redis
      - mqtt-ingestion
    restart:
      unless-stopped
  
  mqtt-ingestion:
    build: 
      context: ../services/mqtt_ingestion
    env_file:
      - .env.mqi
    depends_on:
      - mosquitto
      - redis
    restart:
      unless-stopped

  # gpt-service:
  #   build:
  #     context: ./services/gpt_service
  #   ports:
  #     - "8001:8001"
  #   restart: unless-stopped


      

volumes:
  redis-data:
  timescaledb-data:
