services:

  redis:
    image: redis:8
    ports: 
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
  
  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
      - "9001:9001"
      - "8883:8883"
    volumes:
      - ./mosquitto/:/mosquitto/
    restart: unless-stopped
  
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-example}
      POSTGRES_DB: ${POSTGRES_DB:-iot_data}
    ports:
      - "5432:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis-data:
  timescaledb-data:
