# Generated by Django 4.2.5 on 2024-08-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=20)),
                ('protocol', models.CharField(max_length=20)),
                ('temperature', models.BooleanField(default=False)),
                ('humidity', models.BooleanField(default=False)),
            ],
        ),
    ]
