# Generated by Django 4.2.5 on 2024-10-08 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("iotDashboard", "0001_initial"),
    ]

    operations = [
        # Note: Device model is now managed=False, so we don't modify it in migrations
        # SensorType and Sensor models are also not in current models.py
        # This migration is kept for historical reference but operations are removed
        # to prevent errors with managed=False models
    ]